language: cpp

notifications:
  email: false

branches:
  only:
    - frontend
    - backend
    - cryptor
    - builder
    - auth

sudo: required

before_install:
  - docker --version || true
  - curl -fsSL https://get.docker.com/ | sudo bash
  - docker --version
  - docker pull b1f6c1c4/ballot-builder
  - pip install --user cpp-coveralls

script:
  - docker build -f Dockerfile.build -t b1f6c1c4/ballot-cryptor-build .
  - docker create --name extract b1f6c1c4/ballot-cryptor-build
  - docker cp extract:/root/cryptor ./build
  - docker rm -f extract
  - docker build -t b1f6c1c4/ballot-cryptor ./build

after_success:
  - cd build
  - coveralls --exclude tests --exclude-pattern ".*\.h(pp)?" -b . -n
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push b1f6c1c4/ballot-cryptor
