version: "2.3"
services:

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8888:80"
    links:
      - storage
      - monitor
    networks:
      - ansys-moe

  storage:
    image: ansys-storage
    restart: always
    environment:
      BACKEND_LOG: "${DEBUG_LEVEL}"
      DATA_PATH: "/ansys"
    volumes:
      - /root/ansys-moe:/ansys
    networks:
      - ansys-moe

  monitor:
    image: ansys-monitor
    restart: always
    environment:
      BACKEND_LOG: "${DEBUG_LEVEL}"
      RABBIT_HOST: "${RABBIT_HOST}"
      RABBIT_PORT: "${RABBIT_PORT}"
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASS: "${RABBIT_PASS}"
    networks:
      - ansys-moe

networks:
  ansys-moe:
    driver: bridge
