version: "2.3"
services:

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - storage
      - monitor
      - controller
    networks:
      - prod

  controller:
    image: ansys-controller
    restart: always
    environment:
      BACKEND_LOG: "${DEBUG_LEVEL}"
      ETCD_ENDPOINTS: '["etcd1:2379","etcd2:2379","etcd3:2379"]'
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASS: "${RABBIT_PASS}"
      STORAGE_URL: "http://storage:3000"
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - prod

  storage:
    image: ansys-storage
    restart: always
    environment:
      BACKEND_LOG: "${DEBUG_LEVEL}"
      DATA_PATH: "/ansys"
    volumes:
      - /root/ansys-moe/storage:/ansys
    networks:
      - prod

  monitor:
    image: ansys-monitor
    restart: always
    environment:
      BACKEND_LOG: "${DEBUG_LEVEL}"
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASS: "${RABBIT_PASS}"
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - prod

  rlangd:
    image: ansys-commond
    restart: always
    environment:
      REMOTE_URL: http://nginx
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      RABBIT_USER: "${RABBIT_USER}"
      RABBIT_PASS: "${RABBIT_PASS}"
      RLANG: 2
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - prod

  etcd1:
    image: quay.io/coreos/etcd:v3.2.18
    restart: always
    ports:
      - "23791:2379"
    volumes:
      - /root/ansys-moe/etcd1:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_NAME: etcd1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: ansys-moe-etcd
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
    networks:
      - prod

  etcd2:
    image: quay.io/coreos/etcd:v3.2.18
    restart: always
    ports:
      - "23792:2379"
    volumes:
      - /root/ansys-moe/etcd2:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_NAME: etcd2
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd2:2380
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: ansys-moe-etcd
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd2:2379
    networks:
      - prod

  etcd3:
    image: quay.io/coreos/etcd:v3.2.18
    restart: always
    ports:
      - "23793:2379"
    volumes:
      - /root/ansys-moe/etcd3:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_NAME: etcd3
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd3:2380
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: ansys-moe-etcd
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd3:2379
    networks:
      - prod

  rabbit:
    image: rabbitmq:management-alpine
    hostname: rabbit
    restart: always
    ports:
      - "9511:5672"
      - "9512:15672"
    volumes:
      - /root/ansys-moe/rabbit:/var/lib/rabbitmq/mnesia
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://localhost:15672"]
      interval: 15s
      timeout: 10s
      retries: 8
    networks:
      - prod

networks:
  prod:
    driver: bridge
